spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}
spring.datasource.hikari.connection-timeout=10000

teste.prod=funcionou

frontend.url=${FRONTEND_URL}